#coding=utf-8

q = [{"px": "new", "city": "全国"},
     {"px": "new", "city": "北京"},
     {"px": "new", "city": "上海"},
     {"px": "new", "city": "深圳"},
     {"px": "new", "city": "广州"},
     {"px": "new", "city": "杭州"},
     {"px": "new", "city": "成都"},
     {"px": "new", "city": "南京"},
     {"px": "new", "city": "武汉"},
     {"px": "new", "city": "西安"},
     {"px": "new", "city": "厦门"},
     {"px": "new", "city": "长沙"},
     {"px": "new", "city": "苏州"},
     {"px": "new", "city": "天津"},
     {"px": "new", "city": "重庆"},
     {"px": "new", "city": "郑州"},
     {"px": "new", "city": "青岛"},
     {"px": "new", "city": "合肥"},
     {"px": "new", "city": "福州"},
     {"px": "new", "city": "济南"},
     {"px": "new", "city": "大连"},
     {"px": "new", "city": "珠海"},
     {"px": "new", "city": "无锡"},
     {"px": "new", "city": "佛山"},
     {"px": "new", "city": "东莞"},
     {"px": "new", "city": "宁波"},
     {"px": "new", "city": "常州"},
     {"px": "new", "city": "沈阳"},
     {"px": "new", "city": "石家庄"},
     {"px": "new", "city": "昆明"},
     {"px": "new", "city": "南昌"},
     {"px": "new", "city": "南宁"},
     {"px": "new", "city": "哈尔滨"},
     {"px": "new", "city": "中山"},
     {"px": "new", "city": "惠州"},
     {"px": "new", "city": "贵阳"},
     {"px": "new", "city": "长春"},
     {"px": "new", "city": "太原"},
     {"px": "new", "city": "嘉兴"},
     {"px": "new", "city": "泰安"},
     {"px": "new", "city": "昆山"},
     {"px": "new", "city": "烟台"},
     {"px": "new", "city": "兰州"},
     {"px": "new", "city": "泉州"},
     ]

import traceback
traceback.print_exc()